use crate::emergency_warning::Properties;

// array of tuples stat ename to abbrevation
pub enum State {
    Alabama,
    Arizona,
    Arkansas,
    California,
    Colorado,
    Connecticut,
    Delaware,
    Florida,
    Georgia,
    Hawaii,
    Idaho,
    Illinois,
    Indiana,
    Iowa,
    Kansas,
    Kentucky,
    Louisiana,
    Maine,
    Maryland,
    Massachusetts,
    Michigan,
    Minnesota,
    Mississippi,
    Missouri,
    Montana,
    Nebraska,
    Nevada,
    NewHampshire,
    NewJersey,
    NewMexico,
    NewYork,
    NorthCarolina,
    NorthDakota,
    Ohio,
    Oklahoma,
    Oregon,
    Pennsylvania,
    RhodeIsland,
    SouthCarolina,
    SouthDakota,
    Tennessee,
    Texas,
    Utah,
    Vermont,
    Virginia,
    Washington,
    WestVirginia,
    Wisconsin,
    Wyoming,
}
pub fn state_to_enum(state: &str) -> State {
    // Example: Alabama -> State::Alabama
    match state {
        "alabama" => State::Alabama,
        "arizona" => State::Arizona,
        "arkansas" => State::Arkansas,
        "california" => State::California,
        "colorado" => State::Colorado,
        "connecticut" => State::Connecticut,
        "delaware" => State::Delaware,
        "florida" => State::Florida,
        "georgia" => State::Georgia,
        "hawaii" => State::Hawaii,
        "idaho" => State::Idaho,
        "illinois" => State::Illinois,
        "indiana" => State::Indiana,
        "iowa" => State::Iowa,
        "kansas" => State::Kansas,
        "kentucky" => State::Kentucky,
        "louisiana" => State::Louisiana,
        "maine" => State::Maine,
        "maryland" => State::Maryland,
        "massachusetts" => State::Massachusetts,
        "michigan" => State::Michigan,
        "minnesota" => State::Minnesota,
        "mississippi" => State::Mississippi,
        "missouri" => State::Missouri,
        "montana" => State::Montana,
        "nebraska" => State::Nebraska,
        "nevada" => State::Nevada,
        "new hampshire" => State::NewHampshire,
        "new jersey" => State::NewJersey,
        "new mexico" => State::NewMexico,
        "new york" => State::NewYork,
        "north carolina" => State::NorthCarolina,
        "north dakota" => State::NorthDakota,
        "ohio" => State::Ohio,
        "oklahoma" => State::Oklahoma,
        "oregon" => State::Oregon,
        "pennsylvania" => State::Pennsylvania,
        "rhode island" => State::RhodeIsland,
        "south carolina" => State::SouthCarolina,
        "south dakota" => State::SouthDakota,
        "tennessee" => State::Tennessee,
        "texas" => State::Texas,
        "utah" => State::Utah,
        "vermont" => State::Vermont,
        "virginia" => State::Virginia,
        "washington" => State::Washington,
        "west virginia" => State::WestVirginia,
        "wisconsin" => State::Wisconsin,
        "wyoming" => State::Wyoming,
        _ => panic!("Invalid state"),
    }
}
impl State {
    pub fn abbreviate(&self) -> String {
        // State::Alabama -> AL
        let abbrev = match self {
            State::Alabama => "AL",
            State::Arizona => "AZ",
            State::Arkansas => "AR",
            State::California => "CA",
            State::Colorado => "CO",
            State::Connecticut => "CT",
            State::Delaware => "DE",
            State::Florida => "FL",
            State::Georgia => "GA",
            State::Hawaii => "HI",
            State::Idaho => "ID",
            State::Illinois => "IL",
            State::Indiana => "IN",
            State::Iowa => "IA",
            State::Kansas => "KS",
            State::Kentucky => "KY",
            State::Louisiana => "LA",
            State::Maine => "ME",
            State::Maryland => "MD",
            State::Massachusetts => "MA",
            State::Michigan => "MI",
            State::Minnesota => "MN",
            State::Mississippi => "MS",
            State::Missouri => "MO",
            State::Montana => "MT",
            State::Nebraska => "NE",
            State::Nevada => "NV",
            State::NewHampshire => "NH",
            State::NewJersey => "NJ",
            State::NewMexico => "NM",
            State::NewYork => "NY",
            State::NorthCarolina => "NC",
            State::NorthDakota => "ND",
            State::Ohio => "OH",
            State::Oklahoma => "OK",
            State::Oregon => "OR",
            State::Pennsylvania => "PA",
            State::RhodeIsland => "RI",
            State::SouthCarolina => "SC",
            State::SouthDakota => "SD",
            State::Tennessee => "TN",
            State::Texas => "TX",
            State::Utah => "UT",
            State::Vermont => "VT",
            State::Virginia => "VA",
            State::Washington => "WA",
            State::WestVirginia => "WV",
            State::Wisconsin => "WI",
            State::Wyoming => "WY",
        }
        .to_string();
        abbrev
    }
}
pub fn pretty_print(response: Properties) {
    let response = response.properties;
    println!("Event: {}", response.event);
    println!("Severity: {}", response.severity);
    println!("Certainty: {}", response.certainty);
    println!("Area Description: {}\n", response.areaDesc);
}
